### ISSUE TITLE
Conformance tests for the Gateway APIs

### ISSUE THREAD

**Issue by ZhiminXiang** [knative-sandbox/net-gateway-api#11]
We need to set up the conformance tests with the way we use Gateway APIs so that the various networking implementations (e.g. Istio, contour) could run them and check if they can support those Gateway APIs.

/assign @nak3

**Comment by ZhiminXiang** [comment]
this is the PR https://github.com/knative-sandbox/net-ingressv2/pull/10

**Comment by carlisia** [comment]
This PR: https://github.com/knative-sandbox/net-gateway-api/pull/149 made me think to ask this question:

Should we maintain separate versions of the conformance tests, one for each api-gateway (major) release? For example:
- v0.4.0
- v0.3.0
(I don't think there's value in adding conformance tests for previous releases if we don't have them)

Should we do this as we move forward? Does it make sense?

**Comment by howardjohn** [comment]
Generally I wouldn't invest much effort into v1alpha1 at all. Most implementations are planning to only support v1alpha2 from what I have heard

**Comment by nak3** [comment]
I would like to test the latest version (v0.4.0).
But  v0.4.0 requires k8s lib 0.22 dependency which will be conflict with current knative.dev/pkg. Do we have a good idea to solve the dependency issue even after adding a new controller?

**Comment by nak3** [comment]
For v0.4.0, I am doing it on my personal repo https://github.com/nak3/net-ingressv2
If it should be maintained in knative-sandbox, we should create the new repo. (But I think nobody is interested in reviewing/developing the conformance test :cry: )

**Comment by nak3** [comment]
Closing as the original issue was solved.
