### ISSUE TITLE
[Upstream] If readiness is signalled via. status does it properly implement observeredGeneration

### ISSUE THREAD

**Issue by carlisia** [knative-sandbox/net-gateway-api#364]
Should this be in gateway api's conformance testing?

Ref.: https://github.com/knative-sandbox/net-istio/issues/585.

**Comment by carlisia** [comment]
Closing since this is a dup of an existing issue: https://github.com/knative-sandbox/net-istio/issues/585.

**Comment by carlisia** [comment]
Didn't notice that issue is in the net-istio repo. Reopening.

**Comment by dprotaso** [comment]
I'm updating the conformance test to assert this - https://github.com/kubernetes-sigs/gateway-api/pull/1586

**Comment by dprotaso** [comment]
Upstream conformance changes landed that assert HTTPRoute conditions have observedGeneration

The work to read that info is part of https://github.com/knative-sandbox/net-gateway-api/issues/425
